version: '3.2'
services:
   logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: shop-logstash
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
